//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_CT_HOADON> tb_CT_HOADON { get; set; }
        public virtual DbSet<tb_CT_PHIEUNHAP> tb_CT_PHIEUNHAP { get; set; }
        public virtual DbSet<tb_HOADON> tb_HOADON { get; set; }
        public virtual DbSet<tb_KHACHHANG> tb_KHACHHANG { get; set; }
        public virtual DbSet<tb_NHACC> tb_NHACC { get; set; }
        public virtual DbSet<tb_NHANVIEN> tb_NHANVIEN { get; set; }
        public virtual DbSet<tb_NHOMHH> tb_NHOMHH { get; set; }
        public virtual DbSet<tb_PHIEUNHAP> tb_PHIEUNHAP { get; set; }
        public virtual DbSet<tb_TAIKHOAN> tb_TAIKHOAN { get; set; }
        public virtual DbSet<tb_TONKHO> tb_TONKHO { get; set; }
        public virtual DbSet<tb_HANGHOA> tb_HANGHOA { get; set; }
        public virtual DbSet<view_HANGHOA_WITH_LG_TON> view_HANGHOA_WITH_LG_TON { get; set; }
        public virtual DbSet<view_TONKHO> view_TONKHO { get; set; }
    
        public virtual int sp_TinhTonKho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhTonKho");
        }
    
        public virtual ObjectResult<GetDoanhThuTheoThang_Result> GetDoanhThuTheoThang(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string groupBy, Nullable<int> maNV, Nullable<int> maKH)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var groupByParameter = groupBy != null ?
                new ObjectParameter("GroupBy", groupBy) :
                new ObjectParameter("GroupBy", typeof(string));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDoanhThuTheoThang_Result>("GetDoanhThuTheoThang", startDateParameter, endDateParameter, groupByParameter, maNVParameter, maKHParameter);
        }
    }
}
