//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDbContext : DbContext
    {
        public MyDbContext()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_PHIEUNHAP> tb_PHIEUNHAP { get; set; }
        public virtual DbSet<tb_CT_PHIEUNHAP> tb_CT_PHIEUNHAP { get; set; }
        //public virtual DbSet<tb_CONGTY> tb_CONGTY { get; set; }
        //public virtual DbSet<tb_DONVI> tb_DONVI { get; set; }
        public virtual DbSet<tb_HANGHOA> tb_HANGHOA { get; set; }
        public virtual DbSet<tb_NHACC> tb_NHACC { get; set; }

      //  public virtual DbSet<tb_XUATXU> tb_XUATXU { get; set; }
       // public virtual DbSet<V_FUNC_SYS_RIGHT> V_FUNC_SYS_RIGHT { get; set; }
    }
}
