//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CT_HOADON
    {
        public string MA_CT_HD { get; set; }
        public string MAHD { get; set; }
        public string TENHH { get; set; }
        public string MAHH { get; set; }
        public Nullable<int> SOLUONGCT { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public string DVT { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
