//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HANGHOA
    {
        public string MAHH { get; set; }
        public string TENHH { get; set; }
        public string DVT { get; set; }
        public Nullable<double> GIANHAP { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public string MOTA { get; set; }
        public string MANHOM { get; set; }
        public string NUOCSX { get; set; }
    
        public virtual tb_NHOMHH tb_NHOMHH { get; set; }
    }
}
