//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PHIEUNHAP
    {
        public string MAPN { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string GHICHU { get; set; }
        public string MANV { get; set; }
        public string MANCC { get; set; }
    
        public virtual tb_NHACC tb_NHACC { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
    }
}
