//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TONKHO
    {
        public string MAHH { get; set; }
        public Nullable<int> LG_NHAP { get; set; }
        public Nullable<int> LG_BAN { get; set; }
        public Nullable<int> LG_TON { get; set; }
        public Nullable<double> TRIGIA { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public string TENHH { get; set; }
        public Nullable<int> LG_ANTOAN { get; set; }
    }
}
