//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_HANGHOA_WITH_LG_TON
    {
        public string MAHH { get; set; }
        public string TENHH { get; set; }
        public string DVT { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public int LG_TON { get; set; }
    }
}
